name: Hello World - my first flow

on:
    workflow_dispatch:
        inputs:
            name:
                description: 'Your name'
                required: true
                default: 'World'
    push:
        branches:
            - main
    #     tags:
    #         - 'v*.*.*'
    pull_request:
        branches:
            - main

    # schedule:
    #     - cron: '0 0 * * *' # Runs every day at midnight
    

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Hello world action step
          run: echo "Hello world from my first workflow"
        
        - name: Run tests
          run: echo "Running tests..."

    test:
        runs-on: ubuntu-latest
        
        steps:
        - name: Test job step
          run: echo "This is a test job"
        - name: Echo event name
          run: echo "Triggered by ${{ github.event_name }}"


