name: Runner Test

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Your name'
        required: true
        default: 'World'
  workflow_call:
    inputs:
      name:
        type: string
        default: 'World'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is job 1"
      - run: hostname

  job2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is job 2"
      - run: hostname