name: Secrets Demo

on: 
    workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Secret is $MY_SECRET"
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}